# -*- coding: utf-8 -*-
"""visualization_utils.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UaggwYYCkTVMeLhFyUQXSwhwPtpXGZqB
"""

import folium
import pandas as pd
import numpy as np

from datetime import datetime
from folium import plugins
from folium.plugins import MeasureControl
from folium.plugins import HeatMap


def convert_unix_time(timestamp):
  return datetime.fromtimestamp(timestamp)

def create_heatmap(latitude, longitude, df):

  # initialize heatmap to general austin area
  m = folium.Map(location=[30.266666, -97.733330], zoom_start=14)
  m.add_child(MeasureControl())

  df= df.drop_duplicates(subset=['advertiser_id'], keep='first')
  latitude = latitude.astype(float)
  longitude = longitude.astype(float)

  df = pd.concat([latitude, longitude], axis = 1)
  df = df.dropna(axis=0, subset=['latitude','longitude'])
  heat_data = [[row['latitude'],row['longitude']] for index, row in df.iterrows()]

  HeatMap(heat_data, radius = 20).add_to(m)

  # save heatmap in current directory
  m.save('heatmap.html')

def create_heatmap_through_time(latitude, longitude, df):
  df['location_at'] = df['location_at'].apply(lambda x: convert_unix_time(x))

  # "time" length used is by hour
  return null

def create_individual_map(df):

  # sample random individual from data (for now...)
  df['location_at'] = df['location_at'].apply(lambda x: convert_unix_time(x))
  id = df.sample()['advertiser_id'].values[0]

  # get all available coordinates of randomly sampled individual
  df_ind = df.loc[df_march31['advertiser_id'] == id]

  # sort by time
  df_ind.sort_values(by='location_at')

  # create heatmap
  create_heatmap(df_ind['latitude'], df_ind['longitude'], df)

  # create path map
  df_ind['latitude'] = df_ind['latitude'].astype(float)
  df_ind['longitude'] = df_ind['longitude'].astype(float)

  df_data = df_ind[['latitude', 'longitude']]
  df_data = df_data.dropna(axis=0, subset=['latitude','longitude'])
  data = [[row['latitude'],row['longitude']] for index, row in df_data.iterrows()]

  m = folium.Map(location=[30.266666, -97.733330])
  f1 = folium.FeatureGroup("Individual 1")
  line_1 = folium.vector_layers.PolyLine(data,popup='Path of {}'.format(id),tooltip='Individual_1',color='blue',weight=10).add_to(f1)
  f1.add_to(m)
  folium.LayerControl().add_to(m)

  # save to current directory
  m.save('pathmap.html')

df_march31 = pd.read_csv('31.csv')
create_individual_map(df_march31)